# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import time

# Configuration, please edit

# Data about this site
BLOG_AUTHOR = "Шуйский Николай [krigstask, Ŝtérkrìg]"
BLOG_TITLE = "Päiväcirja"
# This is the main URL for your site. It will be used
# in a prominent link
SITE_URL = "http://my.opera.com/community/"
# This is the URL where nikola's output will be deployed.
# If not set, defaults to SITE_URL
# BASE_URL = "http://my.opera.com/community/"
BLOG_EMAIL = "sterkrig@myopera.com"
BLOG_DESCRIPTION = "None"

# Nikola is multilingual!
#
# Currently supported languages are:
# bg     Bulgarian
# ca     Catalan
# de     German
# el     Greek [NOT gr!]
# en     English
# eo     Esperanto
# es     Spanish
# fa     Persian
# fi     Finnish
# fr     French
# hr     Croatian
# it     Italian
# jp     Japanese
# nl     Dutch
# pt_br  Portuguese (Brasil)
# pl     Polish
# ru     Russian
# sl     Slovenian [NOT sl_si!]
# tr_tr  Turkish (Turkey)
# zh_cn  Chinese (Simplified)
#
# If you want to use Nikola with a non-supported language you have to provide
# a module containing the necessary translations
# (p.e. look at the modules at: ./nikola/data/themes/default/messages/fr.py).
# If a specific post is not translated to a language, then the version
# in the default language will be shown instead.

# What is the default language?
DEFAULT_LANG = "en"

# What other languages do you have?
# The format is {"translationcode" : "path/to/translation" }
# the path will be used as a prefix for the generated pages location
TRANSLATIONS = {
    DEFAULT_LANG: "",
    # Example for another language:
    # "es": "./es",
}

# Links for the sidebar / navigation bar.
# You should provide a key-value pair for each used language.
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ('/archive.html', 'Archives'),
        ('/categories/index.html', 'Tags'),
        ('/rss.xml', 'RSS'),
    ),
}

# Below this point, everything is optional

# While nikola can select a sensible locale for each language,
# sometimes explicit control can come handy.
# In this file we express locales in the string form that
# python's locales will accept in your OS, by example
# "en_US.utf8" in unix-like OS, "English_United States" in Windows.
# LOCALES = dict mapping language --> explicit locale for the languages
# in TRANSLATIONS. You can ommit one or more keys.
# LOCALE_FALLBACK = locale to use when an explicit locale is unavailable
# LOCALE_DEFAULT = locale to use for languages not mentioned in LOCALES; if
# not set the default Nikola mapping is used.

# POSTS and PAGES contains (wildcard, destination, template) tuples.
#
# The wildcard is used to generate a list of reSt source files
# (whatever/thing.txt).
#
# That fragment could have an associated metadata file (whatever/thing.meta),
# and optionally translated files (example for spanish, with code "es"):
#     whatever/thing.txt.es and whatever/thing.meta.es
#
# From those files, a set of HTML fragment files will be generated:
# cache/whatever/thing.html (and maybe cache/whatever/thing.html.es)
#
# These files are combinated with the template to produce rendered
# pages, which will be placed at
# output / TRANSLATIONS[lang] / destination / pagename.html
#
# where "pagename" is the "slug" specified in the metadata file.
#
# The difference between POSTS and PAGES is that POSTS are added
# to feeds and are considered part of a blog, while PAGES are
# just independent HTML pages.
#

POSTS = (
            ("posts/*.rst", "posts", "post.tmpl"),
        )
PAGES = (
            ("stories/*.rst", "stories", "story.tmpl"),
        )

# One or more folders containing files to be copied as-is into the output.
# The format is a dictionary of "source" "relative destination".
# Default is:
# FILES_FOLDERS = {'files': '' }
# Which means copy 'files' into 'output'

# A mapping of languages to file-extensions that represent that language.
# Feel free to add or delete extensions to any list, but don't add any new
# compilers unless you write the interface for it yourself.
#
# 'rest' is reStructuredText
# 'markdown' is MarkDown
# 'html' assumes the file is html and just copies it
COMPILERS = {
        "rest": ('.txt', '.rst'),
        "markdown": ('.md', '.mdown', '.markdown', '.wp'),
        "html": ('.html', '.htm')
        }
        

# Create by default posts in one file format?
# Set to False for two-file posts, with separate metadata.
# ONE_FILE_POSTS = True

# If this is set to True, then posts that are not translated to a language
# LANG will not be visible at all in the pages in that language.
# If set to False, the DEFAULT_LANG version will be displayed for
# untranslated posts.
# HIDE_UNTRANSLATED_POSTS = False

# Paths for different autogenerated bits. These are combined with the
# translation paths.

# Final locations are:
# output / TRANSLATION[lang] / TAG_PATH / index.html (list of tags)
# output / TRANSLATION[lang] / TAG_PATH / tag.html (list of posts for a tag)
# output / TRANSLATION[lang] / TAG_PATH / tag.xml (RSS feed for a tag)
# TAG_PATH = "categories"

# If TAG_PAGES_ARE_INDEXES is set to True, each tag's page will contain
# the posts themselves. If set to False, it will be just a list of links.
# TAG_PAGES_ARE_INDEXES = True

# Final location is output / TRANSLATION[lang] / INDEX_PATH / index-*.html
# INDEX_PATH = ""

# Create per-month archives instead of per-year
# CREATE_MONTHLY_ARCHIVE = False
# Create one large archive instead of per-year
# CREATE_SINGLE_ARCHIVE = False
# Final locations for the archives are:
# output / TRANSLATION[lang] / ARCHIVE_PATH / ARCHIVE_FILENAME
# output / TRANSLATION[lang] / ARCHIVE_PATH / YEAR / index.html
# output / TRANSLATION[lang] / ARCHIVE_PATH / YEAR / MONTH / index.html
# ARCHIVE_PATH = ""
# ARCHIVE_FILENAME = "archive.html"

# Final locations are:
# output / TRANSLATION[lang] / RSS_PATH / rss.xml
# RSS_PATH = ""

# Number of posts in RSS feeds
# FEED_LENGTH = 10

# Slug the Tag URL easier for users to type, special characters are
# often removed or replaced as well.
# SLUG_TAG_PATH = True

# A list of redirection tuples, [("foo/from.html", "/bar/to.html")].
#
# A HTML file will be created in output/foo/from.html that redirects
# to the "/bar/to.html" URL. notice that the "from" side MUST be a
# relative URL.
#
# If you don't need any of these, just set to []
REDIRECTIONS = [(u'Sterkrig/blog/show.dml/27612552/index.html', u'/community//posts/sterkrigblogshowdml27612552.html'), (u'Sterkrig/blog/show.dml/747058/index.html', u'/community//posts/sterkrigblogshowdml747058.html'), (u'Sterkrig/blog/show.dml/1530366/index.html', u'/community//posts/sterkrigblogshowdml1530366.html'), (u'Sterkrig/blog/show.dml/1972422/index.html', u'/community//posts/sterkrigblogshowdml1972422.html'), (u'Sterkrig/blog/show.dml/771570/index.html', u'/community//posts/sterkrigblogshowdml771570.html'), (u'Sterkrig/blog/show.dml/643974/index.html', u'/community//posts/sterkrigblogshowdml643974.html'), (u'Sterkrig/blog/show.dml/687481/index.html', u'/community//posts/sterkrigblogshowdml687481.html'), (u'Sterkrig/blog/show.dml/1425053/index.html', u'/community//posts/sterkrigblogshowdml1425053.html'), (u'Sterkrig/blog/show.dml/1605051/index.html', u'/community//posts/sterkrigblogshowdml1605051.html'), (u'Sterkrig/blog/show.dml/8569941/index.html', u'/community//posts/sterkrigblogshowdml8569941.html'), (u'Sterkrig/blog/show.dml/50529192/index.html', u'/community//posts/sterkrigblogshowdml50529192.html'), (u'Sterkrig/blog/show.dml/3232181/index.html', u'/community//posts/sterkrigblogshowdml3232181.html'), (u'Sterkrig/blog/show.dml/902109/index.html', u'/community//posts/sterkrigblogshowdml902109.html'), (u'Sterkrig/blog/show.dml/58678292/index.html', u'/community//posts/sterkrigblogshowdml58678292.html'), (u'Sterkrig/blog/show.dml/109728022/index.html', u'/community//posts/sterkrigblogshowdml109728022.html'), (u'Sterkrig/blog/show.dml/2833004/index.html', u'/community//posts/sterkrigblogshowdml2833004.html'), (u'Sterkrig/blog/show.dml/1624961/index.html', u'/community//posts/sterkrigblogshowdml1624961.html'), (u'Sterkrig/blog/show.dml/26806801/index.html', u'/community//posts/sterkrigblogshowdml26806801.html'), (u'Sterkrig/blog/show.dml/3097449/index.html', u'/community//posts/sterkrigblogshowdml3097449.html'), (u'Sterkrig/blog/show.dml/5890161/index.html', u'/community//posts/sterkrigblogshowdml5890161.html'), (u'Sterkrig/blog/show.dml/60601332/index.html', u'/community//posts/sterkrigblogshowdml60601332.html'), (u'Sterkrig/blog/show.dml/1006865/index.html', u'/community//posts/sterkrigblogshowdml1006865.html'), (u'Sterkrig/blog/show.dml/2408452/index.html', u'/community//posts/sterkrigblogshowdml2408452.html'), (u'Sterkrig/blog/show.dml/5693911/index.html', u'/community//posts/sterkrigblogshowdml5693911.html'), (u'Sterkrig/blog/show.dml/2378518/index.html', u'/community//posts/sterkrigblogshowdml2378518.html'), (u'Sterkrig/blog/show.dml/586291/index.html', u'/community//posts/sterkrigblogshowdml586291.html'), (u'Sterkrig/blog/show.dml/50529102/index.html', u'/community//posts/sterkrigblogshowdml50529102.html'), (u'Sterkrig/blog/show.dml/838081/index.html', u'/community//posts/sterkrigblogshowdml838081.html'), (u'Sterkrig/blog/show.dml/595703/index.html', u'/community//posts/sterkrigblogshowdml595703.html'), (u'Sterkrig/blog/show.dml/677184/index.html', u'/community//posts/sterkrigblogshowdml677184.html'), (u'Sterkrig/blog/show.dml/734027/index.html', u'/community//posts/sterkrigblogshowdml734027.html'), (u'Sterkrig/blog/show.dml/867403/index.html', u'/community//posts/sterkrigblogshowdml867403.html'), (u'Sterkrig/blog/show.dml/852388/index.html', u'/community//posts/sterkrigblogshowdml852388.html'), (u'Sterkrig/blog/show.dml/964109/index.html', u'/community//posts/sterkrigblogshowdml964109.html'), (u'Sterkrig/blog/show.dml/12712202/index.html', u'/community//posts/sterkrigblogshowdml12712202.html'), (u'Sterkrig/blog/show.dml/585884/index.html', u'/community//posts/sterkrigblogshowdml585884.html'), (u'Sterkrig/blog/show.dml/50019492/index.html', u'/community//posts/sterkrigblogshowdml50019492.html'), (u'Sterkrig/blog/show.dml/2459011/index.html', u'/community//posts/sterkrigblogshowdml2459011.html'), (u'Sterkrig/blog/show.dml/2481211/index.html', u'/community//posts/sterkrigblogshowdml2481211.html'), (u'Sterkrig/blog/show.dml/937393/index.html', u'/community//posts/sterkrigblogshowdml937393.html'), (u'Sterkrig/blog/show.dml/750028/index.html', u'/community//posts/sterkrigblogshowdml750028.html'), (u'Sterkrig/blog/show.dml/609248/index.html', u'/community//posts/sterkrigblogshowdml609248.html'), (u'Sterkrig/blog/show.dml/655310/index.html', u'/community//posts/sterkrigblogshowdml655310.html'), (u'Sterkrig/blog/show.dml/2975982/index.html', u'/community//posts/sterkrigblogshowdml2975982.html'), (u'Sterkrig/blog/show.dml/2803018/index.html', u'/community//posts/sterkrigblogshowdml2803018.html'), (u'Sterkrig/blog/show.dml/40229472/index.html', u'/community//posts/sterkrigblogshowdml40229472.html'), (u'Sterkrig/blog/show.dml/2793013/index.html', u'/community//posts/sterkrigblogshowdml2793013.html'), (u'Sterkrig/blog/show.dml/3280878/index.html', u'/community//posts/sterkrigblogshowdml3280878.html'), (u'Sterkrig/blog/show.dml/708630/index.html', u'/community//posts/sterkrigblogshowdml708630.html'), (u'Sterkrig/blog/show.dml/39834602/index.html', u'/community//posts/sterkrigblogshowdml39834602.html'), (u'Sterkrig/blog/show.dml/1772479/index.html', u'/community//posts/sterkrigblogshowdml1772479.html'), (u'Sterkrig/blog/show.dml/601138/index.html', u'/community//posts/sterkrigblogshowdml601138.html'), (u'Sterkrig/blog/show.dml/1060430/index.html', u'/community//posts/sterkrigblogshowdml1060430.html'), (u'Sterkrig/blog/show.dml/4395281/index.html', u'/community//posts/sterkrigblogshowdml4395281.html'), (u'Sterkrig/blog/show.dml/28826282/index.html', u'/community//posts/sterkrigblogshowdml28826282.html'), (u'Sterkrig/blog/show.dml/1415600/index.html', u'/community//posts/sterkrigblogshowdml1415600.html'), (u'Sterkrig/blog/show.dml/1032129/index.html', u'/community//posts/sterkrigblogshowdml1032129.html'), (u'Sterkrig/blog/show.dml/2964511/index.html', u'/community//posts/sterkrigblogshowdml2964511.html'), (u'Sterkrig/blog/show.dml/2541901/index.html', u'/community//posts/sterkrigblogshowdml2541901.html'), (u'Sterkrig/blog/show.dml/33977812/index.html', u'/community//posts/sterkrigblogshowdml33977812.html'), (u'Sterkrig/blog/show.dml/2609870/index.html', u'/community//posts/sterkrigblogshowdml2609870.html'), (u'Sterkrig/blog/show.dml/1495914/index.html', u'/community//posts/sterkrigblogshowdml1495914.html'), (u'Sterkrig/blog/show.dml/2810827/index.html', u'/community//posts/sterkrigblogshowdml2810827.html'), (u'Sterkrig/blog/show.dml/3006579/index.html', u'/community//posts/sterkrigblogshowdml3006579.html'), (u'Sterkrig/blog/show.dml/630408/index.html', u'/community//posts/sterkrigblogshowdml630408.html'), (u'Sterkrig/blog/show.dml/1639460/index.html', u'/community//posts/sterkrigblogshowdml1639460.html'), (u'Sterkrig/blog/show.dml/731936/index.html', u'/community//posts/sterkrigblogshowdml731936.html'), (u'Sterkrig/blog/show.dml/37080182/index.html', u'/community//posts/sterkrigblogshowdml37080182.html'), (u'Sterkrig/blog/show.dml/1828161/index.html', u'/community//posts/sterkrigblogshowdml1828161.html'), (u'Sterkrig/blog/show.dml/3157754/index.html', u'/community//posts/sterkrigblogshowdml3157754.html'), (u'Sterkrig/blog/show.dml/700635/index.html', u'/community//posts/sterkrigblogshowdml700635.html'), (u'Sterkrig/blog/show.dml/685155/index.html', u'/community//posts/sterkrigblogshowdml685155.html'), (u'Sterkrig/blog/show.dml/4265058/index.html', u'/community//posts/sterkrigblogshowdml4265058.html'), (u'Sterkrig/blog/show.dml/778395/index.html', u'/community//posts/sterkrigblogshowdml778395.html'), (u'Sterkrig/blog/show.dml/46685992/index.html', u'/community//posts/sterkrigblogshowdml46685992.html'), (u'Sterkrig/blog/show.dml/894488/index.html', u'/community//posts/sterkrigblogshowdml894488.html'), (u'Sterkrig/blog/show.dml/1446169/index.html', u'/community//posts/sterkrigblogshowdml1446169.html'), (u'Sterkrig/blog/show.dml/13770712/index.html', u'/community//posts/sterkrigblogshowdml13770712.html'), (u'Sterkrig/blog/show.dml/37950772/index.html', u'/community//posts/sterkrigblogshowdml37950772.html'), (u'Sterkrig/blog/show.dml/765060/index.html', u'/community//posts/sterkrigblogshowdml765060.html'), (u'Sterkrig/blog/show.dml/12670722/index.html', u'/community//posts/sterkrigblogshowdml12670722.html'), (u'Sterkrig/blog/show.dml/2761536/index.html', u'/community//posts/sterkrigblogshowdml2761536.html'), (u'Sterkrig/blog/show.dml/2508601/index.html', u'/community//posts/sterkrigblogshowdml2508601.html'), (u'Sterkrig/blog/show.dml/2821186/index.html', u'/community//posts/sterkrigblogshowdml2821186.html'), (u'Sterkrig/blog/show.dml/2978968/index.html', u'/community//posts/sterkrigblogshowdml2978968.html'), (u'Sterkrig/blog/show.dml/1641783/index.html', u'/community//posts/sterkrigblogshowdml1641783.html'), (u'Sterkrig/blog/show.dml/922804/index.html', u'/community//posts/sterkrigblogshowdml922804.html'), (u'Sterkrig/blog/show.dml/1412348/index.html', u'/community//posts/sterkrigblogshowdml1412348.html'), (u'Sterkrig/blog/show.dml/4058614/index.html', u'/community//posts/sterkrigblogshowdml4058614.html'), (u'Sterkrig/blog/show.dml/57059642/index.html', u'/community//posts/sterkrigblogshowdml57059642.html'), (u'Sterkrig/blog/show.dml/895036/index.html', u'/community//posts/sterkrigblogshowdml895036.html'), (u'Sterkrig/blog/show.dml/2642690/index.html', u'/community//posts/sterkrigblogshowdml2642690.html'), (u'Sterkrig/blog/show.dml/765761/index.html', u'/community//posts/sterkrigblogshowdml765761.html'), (u'Sterkrig/blog/show.dml/2801334/index.html', u'/community//posts/sterkrigblogshowdml2801334.html'), (u'Sterkrig/blog/show.dml/60641572/index.html', u'/community//posts/sterkrigblogshowdml60641572.html'), (u'Sterkrig/blog/show.dml/8095281/index.html', u'/community//posts/sterkrigblogshowdml8095281.html'), (u'Sterkrig/blog/show.dml/875183/index.html', u'/community//posts/sterkrigblogshowdml875183.html'), (u'Sterkrig/blog/show.dml/1573886/index.html', u'/community//posts/sterkrigblogshowdml1573886.html'), (u'Sterkrig/blog/show.dml/678478/index.html', u'/community//posts/sterkrigblogshowdml678478.html'), (u'Sterkrig/blog/show.dml/586270/index.html', u'/community//posts/sterkrigblogshowdml586270.html'), (u'Sterkrig/blog/show.dml/12724762/index.html', u'/community//posts/sterkrigblogshowdml12724762.html'), (u'Sterkrig/blog/show.dml/969328/index.html', u'/community//posts/sterkrigblogshowdml969328.html')]

# Commands to execute to deploy. Can be anything, for example,
# you may use rsync:
# "rsync -rav output/* joe@my.site:/srv/www/site"
# And then do a backup, or ping pingomatic.
# To do manual deployment, set it to []
# DEPLOY_COMMANDS = []

# Where the output site should be located
# If you don't use an absolute path, it will be considered as relative
# to the location of conf.py
# OUTPUT_FOLDER = 'output'

# where the "cache" of partial generated content should be located
# default: 'cache'
# CACHE_FOLDER = 'cache'

# Filters to apply to the output.
# A directory where the keys are either: a file extensions, or
# a tuple of file extensions.
#
# And the value is a list of commands to be applied in order.
#
# Each command must be either:
#
# A string containing a '%s' which will
# be replaced with a filename. The command *must* produce output
# in place.
#
# Or:
#
# A python callable, which will be called with the filename as
# argument.
#
# By default, there are no filters.
#
# Many filters are shipped with Nikola.  A list is available in the manual:
# <http://getnikola.com/handbook.html#post-processing-filters>
# FILTERS = {
#    ".jpg": ["jpegoptim --strip-all -m75 -v %s"],
# }

# Create a gzipped copy of each generated file. Cheap server-side optimization.
# GZIP_FILES = False
# File extensions that will be compressed
# GZIP_EXTENSIONS = ('.txt', '.htm', '.html', '.css', '.js', '.json', '.xml')
# Use an external gzip command? None means no.
# Example: GZIP_COMMAND = "pigz -k {filename}"
# GZIP_COMMAND = None

# #############################################################################
# Image Gallery Options
# #############################################################################

# Galleries are folders in galleries/
# Final location of galleries will be output / GALLERY_PATH / gallery_name
# GALLERY_PATH = "galleries"
# THUMBNAIL_SIZE = 180
# MAX_IMAGE_SIZE = 1280
# USE_FILENAME_AS_TITLE = True
# EXTRA_IMAGE_EXTENSIONS = []
#
# If set to False, it will sort by filename instead. Defaults to True
# GALLERY_SORT_BY_DATE = True

# #############################################################################
# HTML fragments and diverse things that are used by the templates
# #############################################################################

# Data about post-per-page indexes
# INDEXES_TITLE = ""  # If this is empty, the default is BLOG_TITLE
# INDEXES_PAGES = ""  # If this is empty, the default is 'old posts page %d'
# translated

# Name of the theme to use.
THEME = "bootstrap3"

# Color scheme to be used for code blocks. If your theme provides
# "assets/css/code.css" this is ignored.
# Can be any of autumn borland bw colorful default emacs friendly fruity manni
# monokai murphy native pastie perldoc rrt tango trac vim vs
# CODE_COLOR_SCHEME = 'default'

# If you use 'site-reveal' theme you can select several subthemes
# THEME_REVEAL_CONFIG_SUBTHEME = 'sky'
# You can also use: beige/serif/simple/night/default

# Again, if you use 'site-reveal' theme you can select several transitions
# between the slides
# THEME_REVEAL_CONFIG_TRANSITION = 'cube'
# You can also use: page/concave/linear/none/default

# date format used to display post dates.
# (str used by datetime.datetime.strftime)
# DATE_FORMAT = '%Y-%m-%d %H:%M'

# FAVICONS contains (name, file, size) tuples.
# Used for create favicon link like this:
# <link rel="name" href="file" sizes="size"/>
# For creating favicons, take a look at:
# http://www.netmagazine.com/features/create-perfect-favicon
# FAVICONS = {
#     ("icon", "/favicon.ico", "16x16"),
#     ("icon", "/icon_128x128.png", "128x128"),
# }

# Show only teasers in the index pages? Defaults to False.
# INDEX_TEASERS = False

# A HTML fragment with the Read more... link.
# The following tags exist and are replaced for you:
# {link}        A link to the full post page.
# {read_more}   The string “Read more” in the current language.
# {{            A literal { (U+007B LEFT CURLY BRACKET)
# }}            A literal } (U+007D RIGHT CURLY BRACKET)
# READ_MORE_LINK = '<p class="more"><a href="{link}">{read_more}…</a></p>'

# A HTML fragment describing the license, for the sidebar.
LICENSE = ""
# I recommend using the Creative Commons' wizard:
# http://creativecommons.org/choose/
# LICENSE = """
# <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/2.5/ar/">
# <img alt="Creative Commons License BY-NC-SA"
# style="border-width:0; margin-bottom:12px;"
# src="http://i.creativecommons.org/l/by-nc-sa/2.5/ar/88x31.png"></a>"""

# A small copyright notice for the page footer (in HTML).
# Default is ''
CONTENT_FOOTER = 'Contents &copy; {date}         <a href="mailto:{email}">{author}</a> - Powered by         <a href="http://getnikola.com">Nikola</a>         {license}'
CONTENT_FOOTER = CONTENT_FOOTER.format(email=BLOG_EMAIL,
                                       author=BLOG_AUTHOR,
                                       date=time.gmtime().tm_year,
                                       license=LICENSE)

# To use comments, you can choose between different third party comment
# systems, one of "disqus", "livefyre", "intensedebate", "moot",
#                 "googleplus" or "facebook"
# COMMENT_SYSTEM = "disqus"
# And you also need to add your COMMENT_SYSTEM_ID which
# depends on what comment system you use. The default is
# "nikolademo" which is a test account for Disqus. More information
# is in the manual.
# COMMENT_SYSTEM_ID = "nikolademo"

# Enable annotations using annotateit.org?
# If set to False, you can still enable them for individual posts and pages
# setting the "annotations" metadata.
# If set to True, you can disable them for individual posts and pages using
# the "noannotations" metadata.
# ANNOTATIONS = False

# Create index.html for story folders?
# STORY_INDEX = False
# Enable comments on story pages?
# COMMENTS_IN_STORIES = False
# Enable comments on picture gallery pages?
# COMMENTS_IN_GALLERIES = False

# What file should be used for directory indexes?
# Defaults to index.html
# Common other alternatives: default.html for IIS, index.php
# INDEX_FILE = "index.html"

# If a link ends in /index.html,  drop the index.html part.
# http://mysite/foo/bar/index.html => http://mysite/foo/bar/
# (Uses the INDEX_FILE setting, so if that is, say, default.html,
# it will instead /foo/default.html => /foo)
# (Note: This was briefly STRIP_INDEX_HTML in v 5.4.3 and 5.4.4)
# Default = False
# STRIP_INDEXES = False

# Should the sitemap list directories which only include other directories
# and no files.
# Default to True
# If this is False
# e.g. /2012 includes only /01, /02, /03, /04, ...: don't add it to the sitemap
# if /2012 includes any files (including index.html)... add it to the sitemap
# SITEMAP_INCLUDE_FILELESS_DIRS = True

# Instead of putting files in <slug>.html, put them in
# <slug>/index.html. Also enables STRIP_INDEXES
# This can be disabled on a per-page/post basis by adding
#    .. pretty_url: False
# to the metadata
# PRETTY_URLS = False

# If True, publish future dated posts right away instead of scheduling them.
# Defaults to False.
# FUTURE_IS_NOW = False

# If True, future dated posts are allowed in deployed output
# Only the individual posts are published/deployed; not in indexes/sitemap
# Generally, you want FUTURE_IS_NOW and DEPLOY_FUTURE to be the same value.
# DEPLOY_FUTURE = False
# If False, draft posts will not be deployed
# DEPLOY_DRAFTS = True

# Allows scheduling of posts using the rule specified here (new_post -s)
# Specify an iCal Recurrence Rule: http://www.kanzaki.com/docs/ical/rrule.html
# SCHEDULE_RULE = ''
# If True, use the scheduling rule to all posts by default
# SCHEDULE_ALL = False
# If True, schedules post to today if possible, even if scheduled hour is over
# SCHEDULE_FORCE_TODAY = False

# Do you want a add a Mathjax config file?
# MATHJAX_CONFIG = ""

# If you are using the compile-ipynb plugin, just add this one:
#MATHJAX_CONFIG = """
#<script type="text/x-mathjax-config">
#MathJax.Hub.Config({
#    tex2jax: {
#        inlineMath: [ ['$','$'], ["\\\(","\\\)"] ],
#        displayMath: [ ['$$','$$'], ["\\\[","\\\]"] ]
#    },
#    displayAlign: 'left', // Change this to 'center' to center equations.
#    "HTML-CSS": {
#        styles: {'.MathJax_Display': {"margin": 0}}
#    }
#});
#</script>
#"""

# Do you want to customize the nbconversion of your IPython notebook?
# IPYNB_CONFIG = {}
# With the following example configuracion you can use a custom jinja template
# called `toggle.tpl` which has to be located in your site/blog main folder:
# IPYNB_CONFIG = {'Exporter':{'template_file': 'toggle'}}

# What MarkDown extensions to enable?
# You will also get gist, nikola and podcast because those are
# done in the code, hope you don't mind ;-)
# MARKDOWN_EXTENSIONS = ['fenced_code', 'codehilite']

# Social buttons. This is sample code for AddThis (which was the default for a
# long time). Insert anything you want here, or even make it empty.
# SOCIAL_BUTTONS_CODE = """
# <!-- Social buttons -->
# <div id="addthisbox" class="addthis_toolbox addthis_peekaboo_style addthis_default_style addthis_label_style addthis_32x32_style">
# <a class="addthis_button_more">Share</a>
# <ul><li><a class="addthis_button_facebook"></a>
# <li><a class="addthis_button_google_plusone_share"></a>
# <li><a class="addthis_button_linkedin"></a>
# <li><a class="addthis_button_twitter"></a>
# </ul>
# </div>
# <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f7088a56bb93798"></script>
# <!-- End of social buttons -->
# """

# Hide link to source for the posts?
# HIDE_SOURCELINK = False
# Copy the source files for your pages?
# Setting it to False implies HIDE_SOURCELINK = True
# COPY_SOURCES = True

# Modify the number of Post per Index Page
# Defaults to 10
# INDEX_DISPLAY_POST_COUNT = 10

# RSS_LINK is a HTML fragment to link the RSS or Atom feeds. If set to None,
# the base.tmpl will use the feed Nikola generates. However, you may want to
# change it for a feedburner feed or something else.
# RSS_LINK = None

# Show only teasers in the RSS feed? Default to True
# RSS_TEASERS = True

# A search form to search this site, for the sidebar. You can use a google
# custom search (http://www.google.com/cse/)
# Or a duckduckgo search: https://duckduckgo.com/search_box.html
# Default is no search form.
# SEARCH_FORM = ""
#
# This search form works for any site and looks good in the "site" theme where
# it appears on the navigation bar:
#
#SEARCH_FORM = """
#<!-- Custom search -->
#<form method="get" id="search" action="http://duckduckgo.com/"
# class="navbar-form pull-left">
#<input type="hidden" name="sites" value="%s"/>
#<input type="hidden" name="k8" value="#444444"/>
#<input type="hidden" name="k9" value="#D51920"/>
#<input type="hidden" name="kt" value="h"/>
#<input type="text" name="q" maxlength="255"
# placeholder="Search&hellip;" class="span2" style="margin-top: 4px;"/>
#<input type="submit" value="DuckDuckGo Search" style="visibility: hidden;" />
#</form>
#<!-- End of custom search -->
#""" % SITE_URL
#
# If you prefer a google search form, here's an example that should just work:
#SEARCH_FORM = """
#<!-- Custom search with google-->
#<form id="search" action="http://google.com/search" method="get" class="navbar-form pull-left">
#<input type="hidden" name="q" value="site:%s" />
#<input type="text" name="q" maxlength="255" results="0" placeholder="Search"/>
#</form>
#<!-- End of custom search -->
#""" % SITE_URL

# Also, there is a local search plugin you can use, based on Tipue, but it requires setting several
# options:

# SEARCH_FORM = """
# <span class="navbar-form pull-left">
# <input type="text" id="tipue_search_input">
# </span>"""
#
# BODY_END = """
# <script type="text/javascript" src="/assets/js/tipuesearch_set.js"></script>
# <script type="text/javascript" src="/assets/js/tipuesearch.js"></script>
# <script type="text/javascript">
# $(document).ready(function() {
    # $('#tipue_search_input').tipuesearch({
        # 'mode': 'json',
        # 'contentLocation': '/assets/js/tipuesearch_content.json',
        # 'showUrl': false
    # });
# });
# </script>
# """

# EXTRA_HEAD_DATA = """
# <link rel="stylesheet" type="text/css" href="/assets/css/tipuesearch.css">
# <div id="tipue_search_content" style="margin-left: auto; margin-right: auto; padding: 20px;"></div>
# """
# ENABLED_EXTRAS = ['local_search']
#


# Use content distribution networks for jquery and twitter-bootstrap css and js
# If this is True, jquery is served from the Google CDN and twitter-bootstrap
# is served from the NetDNA CDN
# Set this to False if you want to host your site without requiring access to
# external resources.
# USE_CDN = False

# Extra things you want in the pages HEAD tag. This will be added right
# before </HEAD>
# EXTRA_HEAD_DATA = ""
# Google analytics or whatever else you use. Added to the bottom of <body>
# in the default template (base.tmpl).
# BODY_END = ""

# The possibility to extract metadata from the filename by using a
# regular expression.
# To make it work you need to name parts of your regular expression.
# The following names will be used to extract metadata:
# - title
# - slug
# - date
# - tags
# - link
# - description
#
# An example re is the following:
# '(?P<date>\d{4}-\d{2}-\d{2})-(?P<slug>.*)-(?P<title>.*)\.md'
# FILE_METADATA_REGEXP = None

# Additional metadata that is added to a post when creating a new_post
# ADDITIONAL_METADATA = {}

# Nikola supports Twitter Card summaries / Open Graph.
# Twitter cards make it possible for you to attach media to Tweets
# that link to your content.
#
# IMPORTANT:
# Please note, that you need to opt-in for using Twitter Cards!
# To do this please visit
# https://dev.twitter.com/form/participate-twitter-cards
#
# Uncomment and modify to following lines to match your accounts.
# Specifying the id for either 'site' or 'creator' will be preferred
# over the cleartext username. Specifying an ID is not necessary.
# Displaying images is currently not supported.
# TWITTER_CARD = {
#     # 'use_twitter_cards': True,  # enable Twitter Cards / Open Graph
#     # 'site': '@website',  # twitter nick for the website
#     # 'site:id': 123456,  # Same as site, but the website's Twitter user ID
#                           # instead.
#     # 'creator': '@username',  # Username for the content creator / author.
#     # 'creator:id': 654321,  # Same as creator, but the Twitter user's ID.
# }


# Post's dates are considered in GMT by default, if you want to use
# another timezone, please set TIMEZONE to match. Check the available
# list from Wikipedia:
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Also, if you want to use a different timezone in some of your posts,
# you can use W3C-DTF Format (ex. 2012-03-30T23:00:00+02:00)
#
# TIMEZONE = 'Europe/Zurich'

# If webassets is installed, bundle JS and CSS to make site loading faster
# USE_BUNDLES = True

# Plugins you don't want to use. Be careful :-)
# DISABLED_PLUGINS = ["render_galleries"]

# Experimental plugins - use at your own risk.
# They probably need some manual adjustments - please see their respective
# readme.
# ENABLED_EXTRAS = [
#     'planetoid',
#     'ipynb',
#     'local_search',
#     'render_mustache',
# ]

# List of regular expressions, links matching them will always be considered
# valid by "nikola check -l"
# LINK_CHECK_WHITELIST = []

# If set to True, enable optional hyphenation in your posts (requires pyphen)
# HYPHENATE = False

# You can configure the logging handlers installed as plugins or change the
# log level of the default stdout handler.
LOGGING_HANDLERS = {
    'stderr': {'loglevel': 'WARNING', 'bubble': True},
    #'smtp': {
    #    'from_addr': 'test-errors@example.com',
    #    'recipients': ('test@example.com'),
    #    'credentials':('testusername', 'password'),
    #    'server_addr': ('127.0.0.1', 25),
    #    'secure': (),
    #    'level': 'DEBUG',
    #    'bubble': True
    #}
}

# Put in global_context things you want available on all your templates.
# It can be anything, data, functions, modules, etc.

GLOBAL_CONTEXT = {}
